### ISSUE TITLE
关于怀旧服跳转bug

### ISSUE THREAD

**Issue by WithoutHair** [JX3BOX/origin#1]
正式服/index路由下直接点击怀旧服跳转会二次跳转回正式服

**Comment by iRuxu** [comment]
需要进一步说明问题或提供地址。
/index会固定跳转到www.jx3box.com域名
/origin会固定跳转到origin.jx3box.com域名

**Comment by iRuxu** [comment]
已知问题是更新nginx配置出了点问题，昨日已修复。
